# This is a basic workflow to help you get started with Actions

name:  Automated API tests using Postman CLI

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{secrets.API_KEY}} 
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Postman HW.json" -e "api-hw-4.postman_environment.json"



        
